// angular/AngularNodeJs/src/app/account/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AccountService } from 'src/app/shared/services/account.service';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { FormService } from 'src/app/shared/services/form.service';
import { LoginAccountRequestView } from 'src/app/shared/entities/account.views/requests/login-account.request.view';
import { TokenHelper } from 'src/app/shared/helpers/token.helper';
import { Router } from '@angular/router';
import { UserHelper } from 'src/app/shared/helpers/user.helper';
import { UserDto } from 'src/app/shared/dtos/users/user-dto';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  public loginForm: FormGroup;
  public loginFormSubmitted: boolean = false;
  public modelRequest: LoginAccountRequestView = new LoginAccountRequestView();

  constructor(
    private accountService: AccountService,
    private formService: FormService,
    private tokenHelper: TokenHelper,
    private userHelper: UserHelper,
    private router: Router) {
    this.initForm();
   }

  ngOnInit() {
  }

  private initForm(): void {
    this.loginForm = new FormGroup({
      name: new FormControl('', [Validators.required]),
      password: new FormControl('', [Validators.required])
    });
  }

  checkIfDisplayInputError(inputName: string): boolean {
    return this.formService.checkIfDisplayInputError(inputName, this.loginFormSubmitted, this.loginForm);
  }

  async login(){
    this.loginFormSubmitted = true;
    let result = await this.accountService.login(this.modelRequest).toPromise();
    if (result && result.token) {
      let model = new UserDto();
      model._id = result.user._id;
      model.name = result.user.name;
      model.address = result.user.address;
      model.telephone = result.user.telephone;
      this.tokenHelper.setToken(result.token);
      this.userHelper.setCurrentUser(model);
      this.tokenHelper.tokenOutputEmit.emit(result.token);
      this.router.navigate(["/shop-client/list-products-page"]);
    } else {
      this.router.navigate(["/account/access-denied-page"]);
    }
    this.loginFormSubmitted = false;
  }
}

<div class="card">
  <div class="card-body">
    <div class="form" [formGroup]="loginForm">
      <div class="form-group mb-2">
        <label for="inputUserName">Name</label>
        <input type="text" class="form-control" id="inputUserName" placeholder="User Name" formControlName="name"
          [(ngModel)]="modelRequest.name" [ngClass]="checkIfDisplayInputError('name')?'is-invalid':''">
        <div class="invalid-form-errors" *ngIf="checkIfDisplayInputError('name')">
          <em *ngIf="loginForm.get('name').hasError('required')">Name cannot be empty</em>
        </div>
      </div>
      <div class="form-group mb-2">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password" formControlName="password"
          [(ngModel)]="modelRequest.password" [ngClass]="checkIfDisplayInputError('password')?'is-invalid':''">
        <div class="invalid-form-errors" *ngIf="checkIfDisplayInputError('password')">
          <em *ngIf="loginForm.get('password').hasError('required')">Password cannot be empty</em>
        </div>
      </div>
      <input type="button" class="btn btn-primary mb-2" value="Log in" (click)="login()"/>
    </div>
  </div>
</div>

// react/react-redux-app/src/account/components/login/login.component.tsx
import * as React from 'react';

/** Stylesheet Imports */
import './login.component.css';
import { LoginState } from '../../containers/login.container';

export type LoginProps = {
    loginFormSubmitted: boolean,
    login: () => void
}

export default class LoginComponent extends React.Component<LoginProps, LoginState> {
    login() {
        this.props.login();
    }

    checkIfDisplayInputError(control: string) {
        return false;
    }

    hasError(control: string, error: string) {
        return false;
    }

    renderError(control: string) {
        if (this.hasError(control, 'required')) {
            return <em>Name cannot be empty</em>;
        }
    }

    renderErrors(control: string) {
        if (this.checkIfDisplayInputError(control)) {
            return <div className="invalid-form-errors">
                {this.renderError(control)}
            </div>
        }
    }

    render() {
        return (
            <div className="card">
                <div className="card-body">
                    <div className="form">
                        <div className="form-group mb-2">
                            <label htmlFor="inputUserName">Name</label>
                            <input type="text" className="form-control" id="inputUserName" placeholder="User Name" />
                            {this.renderErrors('name')}
                        </div>
                        <div className="form-group mb-2">
                            <label htmlFor="inputPassword">Password</label>
                            <input type="password" className="form-control" id="inputPassword" placeholder="Password" />
                            {this.renderErrors('password')}
                        </div>
                        <input type="button" className="btn btn-primary mb-2" value="Log in" onClick={(e) => this.login()} />
                    </div >
                </div >
            </div>
        )
    }
}
