// react/react-redux-app/src/shared/components/header-component/header.component.tsx
import React, { Component } from 'react'
import { HeaderState } from '../../../containers/header.container';
import { UserDto } from '../../dtos/users/user-dto';

export type HeaderProps = {
  isUserLoggedIn: boolean,
  isUserAdmin: boolean,
  user: UserDto,
  logout: () => void
}

export default class HeaderComponent extends Component<HeaderProps, HeaderState> {
  logout() {
    this.props.logout();
  }

  renderUserName = () => {
    const props = this.props
    if(props.isUserLoggedIn){
      return <div>Hello {props.user.name}</div>;
    }
    return;
  }

  renderAdminLinks = () => {
    const props = this.props;
    if(props.isUserLoggedIn && props.isUserAdmin){
      return     <li className="nav-item dropdown">
      <a className="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        Admin
      </a>
      <div className="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
        <a className="dropdown-item" href="/shop-admin/add-product-page">Add Product</a>
        <a className="dropdown-item" href="/shop-admin/add-category-page">Add Category</a>
      </div>
    </li>;
    }
    return;
  }

  renderLoginLink = () => {
    const props = this.props;
    if(!props.isUserLoggedIn){
      return <li className="nav-item">
      <a className="nav-link" href="/account/login">Login</a>
      </li>;
    }
    return;
  }

  renderLogoutLink = () => {
    const props = this.props;
    if(!props.isUserLoggedIn){
      return <li className="nav-item">
      <a className="nav-link" onClick={(e) => this.logout()}>Logout</a>
      </li>;
    }
    return;
  }

  renderRegisterLink = () => {
    const props = this.props;
    if(!props.isUserLoggedIn){
      return <li className="nav-item">
      <a className="nav-link" href="account/register">Register</a>
    </li>;
    }
    return;
  }

  render() {
    const props = this.props
    return <div>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <a className="navbar-brand" href="#">Store</a>
        <div className="mr-auto mt-2 mt-lg-0">
        </div>
        <div style={{color: 'rgba(255,255,255,.5)'}}>
          {this.renderUserName()}
        </div>
        <ul className="navbar-nav">
          {this.renderAdminLinks()}
          {this.renderLoginLink()}
          {this.renderLogoutLink()}
          {this.renderRegisterLink()}
        </ul>
        <form className="form-inline my-2 my-lg-0">
          <input className="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"/>
          <button className="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>
    </div>
  }
}

// angular/AngularNodeJs/src/app/shared/components/layout/header-component/header-component.component.ts
import { Component, OnInit } from '@angular/core';
import { TokenHelper } from 'src/app/shared/helpers/token.helper';
import { UserHelper } from 'src/app/shared/helpers/user.helper';
import { UserDto } from 'src/app/shared/dtos/users/user-dto';
import { UserRoleTypeDto } from 'src/app/shared/dtos/enums/user-role-type-dto';

@Component({
  selector: 'app-header-component',
  templateUrl: './header-component.component.html',
  styleUrls: ['./header-component.component.scss']
})
export class HeaderComponentComponent implements OnInit {
  public isUserLoggedIn: boolean = false;
  public isUserAdmin: boolean = false;
  public user: UserDto = new UserDto();

  constructor(private tokenHelper: TokenHelper,
    private userHelper: UserHelper) { }

  ngOnInit() {
    this.loadCurrentUser();
  }

  private loadCurrentUser(): void {
    this.tokenHelper.getTokenEmitter().subscribe(token => {
      if (token) {
        this.isUserLoggedIn = true;
      }
    });
    if (this.tokenHelper.isExist()) {
      this.isUserLoggedIn = true;
    }
    this.user = this.userHelper.getCurrentUser();
    if(this.user){
      this.isUserAdmin = this.user.role === UserRoleTypeDto.Admin;
    }
  }

  public logout(){
    this.tokenHelper.removeToken();
    this.userHelper.clearCurrentUser();
    this.isUserLoggedIn = false;
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Store</a>
  <div class="mr-auto mt-2 mt-lg-0">
  </div>
  <div style="color: rgba(255,255,255,.5);">
    <div *ngIf="isUserLoggedIn">Hello {{user?.name}}</div>
  </div>
  <ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false" *ngIf="isUserLoggedIn && isUserAdmin">
        Admin
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
        <a class="dropdown-item" routerLink="shop-admin/add-product-page">Add Product</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="account/login" *ngIf="!isUserLoggedIn">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" *ngIf="isUserLoggedIn" (click)="logout()">Logout</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" routerLink="account/register" *ngIf="!isUserLoggedIn">Register</a>
    </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
