// angular/AngularNodeJs/src/app/shared/components/layout/sidebar-component/sidebar-component.component.ts
import { Component, OnInit } from '@angular/core';
import { ShopClientService } from 'src/app/shared/services/shop-client.service';
import { CategoryDto } from 'src/app/shared/dtos/categories/category-dto';

@Component({
  selector: 'app-sidebar-component',
  templateUrl: './sidebar-component.component.html',
  styleUrls: ['./sidebar-component.component.scss']
})
export class SidebarComponentComponent implements OnInit {
  public responseModel: Array<CategoryDto> = [];
  constructor(private shopClientService: ShopClientService) { }

  ngOnInit() {
    this.loadData();
  }

  async loadData(){
    this.responseModel = await this.shopClientService.getAllCategories().toPromise();
  }
}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 col-xs-11 p-l-2 p-t-2 hamburger">
      <a href="#sidebar" data-toggle="collapse"><i class="fa fa-navicon fa-lg"></i></a>
    </div>
    <div class="col-md-3 col-xs-1 p-l-0 p-r-0 collapse in" id="sidebar">
      <div class="list-group panel">
        <ng-template #recursiveList let-responseModel>
          <div *ngFor="let item of responseModel">
            <a href="#menu{{item._id}}" class="list-group-item collapsed" data-toggle="collapse" aria-expanded="false">
              <span class="hidden-sm-down">{{item.name}}</span>
            </a>
            <div class="collapse" id="menu{{item._id}}">
              <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: item.subcategories }"></ng-container>
            </div>
          </div>
        </ng-template>
        <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: responseModel }"></ng-container>
      </div>
    </div>
  </div>
</div>

// react/react-redux-app/src/shared/components/sidebar-component/sidebar.component.tsx
import React, { Component } from 'react'
import './sidebar.component.css'
import { SidebarState } from '../../../containers/sidebar.container';
import { CategoryDto } from '../../dtos/categories/category-dto';

export type SidebarProps = {
  responseModel: Array<CategoryDto>,
  goToProductsByCategoryPage: (category: CategoryDto) => void
}

class SidebarComponent extends Component<SidebarProps, SidebarState> {
  goToProductsByCategoryPage(category: CategoryDto){
    this.props.goToProductsByCategoryPage(category);
  }

  render() {
    return <div className="container-fluid">
    <div className="row">
      <div className="col-md-9 col-xs-11 p-l-2 p-t-2 hamburger">
        <a href="#sidebar" data-toggle="collapse"><i className="fa fa-navicon fa-lg"></i></a>
      </div>
      <div className="col-md-3 col-xs-1 p-l-0 p-r-0 collapse in" id="sidebar">
        <div className="list-group panel">
          {this.renderTemplate(this.props.responseModel)}
        </div>
      </div>
    </div>
  </div>
  }

  renderTemplate(categories:any){
    if(categories && categories.length > 0){
      let items = categories.map((item: any) => {
        return <div>{this.renderMenuItem(item)}</div>
      });
      return items;
    }
  }

  renderMenuItem(item: any){
    return <div> <a href="#menu{{item._id}}" className="list-group-item collapsed" data-toggle="collapse" aria-expanded="false" onClick={() => this.goToProductsByCategoryPage(item)}>
    <span className="hidden-sm-down">{item.name}</span>
    </a>
    <div className="collapse" id="menu{{item._id}}">
       {this.renderTemplate(item.subcategories)} 
    </div>
    </div>
  }
}

export default SidebarComponent
