// react/react-redux-app/src/shared/guards/logged.guard.tsx
import { Route, Redirect } from "react-router";
import React, { Component }  from 'react';
import { TokenHelper } from "../helpers/token.helper";

export const LoggedRoute = ({ component: Component, ...rest }: any) => (
    <Route {...rest} render={(props) => {
      let tokenHelper = new TokenHelper();
      let token = tokenHelper.getToken();
      if (token) {
        return <Component {...props} />
      }
      return <Redirect to={{
        pathname: '/Login',
        state: { from: props.location }
      }}/>;
    }} />
 );

// angular/AngularNodeJs/src/app/shared/guards/logged.guard.ts
import { Injectable } from '@angular/core';
import { ActivatedRouteSnapshot, RouterStateSnapshot, CanActivate, Router } from '@angular/router';
import { TokenHelper } from '../helpers/token.helper';

@Injectable({
  providedIn: 'root'
})
export class LoggedGuard implements CanActivate {
  constructor(
    private tokenHelper: TokenHelper,
    private router: Router) { }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean {
    let token = this.tokenHelper.getToken();
    if (token) {
      return true;
    }
    this.router.navigate(['/account/access-denied-page']);
    return false;
  }
}
